trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
        addToPath: true
        architecture: 'x64'
    - script: pip install -r requirements.txt
      displayName: 'Installing dependencies'
    - script: python -m build --outdir $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - script: pip install twine
    - task: TwineAuthenticate@1
      inputs:
        feedUrl: 'https://pkgs.dev.azure.com/francisco0808/_packaging/mypypi/pypi/upload/'
        artifactFeed: 'mypypi'
    #- script: python -m twine upload --config-file $(PYPIRC_PATH) -r mypypi  $(Build.ArtifactStagingDirectory)/*
    #  displayName: Publish python package to Artifacts
    - script: |
        (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
        && sudo mkdir -p -m 755 /etc/apt/keyrings \
        && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
        && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
        && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y