name: localchat-api

on:
  workflow_dispatch:

env:
  tag: latest

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
        
      - name: Login into Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to Dockerhub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: franciscofilho/fastapi-chat:latest
  
