name: localchat-api

on:
  workflow_dispatch:

env:
  tag: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        id: build-image
        run: echo 'Hello world'
  
